import type { DashboardData } from "./data";

export const demoDashboardData: DashboardData = {
  summary: {
    user_id: "demo-user",
    trip_count: 42,
    total_distance_km: 386.4,
    estimated_co2e_kg: 28.7,
    avoided_co2e_kg: 72.9,
    last_trip_on: "2026-07-02",
  },
  recentTrips: [
    {
      id: "demo-001",
      origin: "Home",
      destination: "Startup incubator",
      distance_km: 8.4,
      travel_mode: "transit",
      estimated_co2e_kg: 0.7,
      avoided_co2e_kg: 1.4,
      occurred_on: "2026-07-02",
    },
    {
      id: "demo-002",
      origin: "Campus station",
      destination: "Partner meeting",
      distance_km: 4.2,
      travel_mode: "bike",
      estimated_co2e_kg: 0,
      avoided_co2e_kg: 0.9,
      occurred_on: "2026-07-01",
    },
    {
      id: "demo-003",
      origin: "Coworking space",
      destination: "Prototype lab",
      distance_km: 13.7,
      travel_mode: "ev",
      estimated_co2e_kg: 1.1,
      avoided_co2e_kg: 1.8,
      occurred_on: "2026-06-30",
    },
    {
      id: "demo-004",
      origin: "Home",
      destination: "Local market",
      distance_km: 2.1,
      travel_mode: "walk",
      estimated_co2e_kg: 0,
      avoided_co2e_kg: 0.4,
      occurred_on: "2026-06-29",
    },
    {
      id: "demo-005",
      origin: "Office",
      destination: "Investor coffee chat",
      distance_km: 6.8,
      travel_mode: "carpool",
      estimated_co2e_kg: 0.9,
      avoided_co2e_kg: 0.7,
      occurred_on: "2026-06-28",
    },
    {
      id: "demo-006",
      origin: "Home",
      destination: "Design review",
      distance_km: 9.5,
      travel_mode: "transit",
      estimated_co2e_kg: 0.8,
      avoided_co2e_kg: 1.6,
      occurred_on: "2026-06-27",
    },
  ],
};
